FROM python:latest

RUN mkdir /app
WORKDIR /app

ADD web_scraper /app/web_scraper

RUN apt-get update \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN apt-get -y install curl

RUN groupadd -g 799 aggregator && \
    useradd -r -u 999 -g aggregator aggregator

ADD --chown=aggregator:aggregator web_scraper/requirements.txt /app

WORKDIR /app
RUN pip3 install Flask
RUN pip3 install -r /app/requirements.txt

USER aggregator

COPY web_scraper/wsgi.py /app
COPY web_scraper/entrypoint.sh /app
COPY web_scraper/celery_entrypoint.sh /app

RUN chmod +x ./entrypoint.sh
RUN chmod +x ./celery_entrypoint.sh

CMD [ "python", "./wsgi.py" ]